import type { Metadata } from "next";
import { Azeret_Mono } from "next/font/google"
import "./globals.css";
import Sidebar from "@/components/layout/sidebar";
import Header from "@/components/layout/header";
const azeretMono = Azeret_Mono({
    subsets: ['latin']
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col md:flex-row ${azeretMono.className} antialiased h-screen`}
      >
      <Sidebar/>
      <main className="flex flex-col gap-3 py-6 px-2 lg:py-12 lg:pr-12 w-full">
          <Header />
          {children}
      </main>
      </body>
    </html>
  );
}
